### ISSUE TITLE
Requirements for 2024-3.0 conda envs

### ISSUE THREAD

**Issue by mrakitin** [nsls2-conda-envs/nsls2-collection-tiled#42]
- [x] `nslsii` from conda-forge with `pycryptodome` dependency (remove this explicit )
- [x] bluesky 1.13.0a6 (?, all latest changes should be released)
  - [ ] #47
- [x] `ophyd-async` v0.5.1+
- [x] `tiled` v0.1.0b10
- [x] `hextools`
- [x] `refuse` (https://pypi.org/project/refuse/, no conda-forge package)
- [x] `juliaup` (https://anaconda.org/conda-forge/juliaup)
- [x] `dioptas`
- [x] `h5json` (https://hdf5-json.readthedocs.io/en/latest/tools/h5json.html)
- [x] `redis-json-dict` v0.2.1 (https://github.com/conda-forge/redis-json-dict-feedstock/pull/1)
- [x] `pixi` (https://anaconda.org/conda-forge/pixi)

**Comment by hyperrealist** [comment]
Could we add `refuse` to the list? It is a python interface for libfuse. BMM is experimenting with it to provide a FUSE Mirror file system for certain data sec use cases, and potentially other beamlines may end up needing it.

https://github.com/pleiszenburg/refuse

`pip install refuse`

**Comment by jwlodek** [comment]
PDF has requested newer version of dioptas which they say they use from the conda env. Not sure if that is in one of our standard envs vs if it is some custom env

**Comment by mrakitin** [comment]
https://anaconda.org/briantoby/gsas2pkg/files

**Comment by mrakitin** [comment]
That's the list of packages we get:
```bash
❯ grep -e "nslsii=\|bluesky=\|event-model=\|ophyd-async=\|tiled=\|databroker=\|hextools=\|refuse=\|juliaup=\|dioptas=\|h5json=\|redis-json-dict=\|pixi=\|pyarrow=\|opentelemetry\|deprecated=" 2024-3.0-py312-tiled.yml | cut -d'-' -f2- | sed 's/^ *//g' | sort -u
bluesky==1.13
databroker=2.0.0b45=pyhd8ed1ab_0
deprecated==1.2.14
dioptas=0.5.9=py312h98912ed_2
event-model=1.21.0=pyhd8ed1ab_0
h5json==1.1.3
hextools=0.2.1=pyhd8ed1ab_0
juliaup=1.17.10=h8fae777_0
nslsii=0.10.7=py312h7900ff3_0
opentelemetry-api==1.27.0
ophyd-async==0.7.0
pixi=0.34.0=hbebc5b9_0
pyarrow=18.0.0=py312h9cebb41_0
redis-json-dict=0.2.1=pyhd8ed1ab_0
refuse==0.0.4
tiled=0.1.0b10=hd8ed1ab_0
```
